### ISSUE TITLE
show method error

### ISSUE THREAD

**Issue by drvafa** [oneHamidreza/MeowBottomNavigation#14]
// when click on item 3  , set current item = 1
bottomNavigation.show(1,true);

This function has a problem
![Screenshot_1559064773](https://user-images.githubusercontent.com/16055760/58499177-d4fcf000-8194-11e9-9367-fc62657c429a.png)

**Comment by shetmobile** [comment]
i will check it.

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.

**Comment by oneHamidreza** [comment]
I tested and it worked. check `v1.3.1`.

**Comment by TidelxD** [comment]
https://github.com/oneHamidreza/MeowBottomNavigation/issues/34
 Im Getting Same error on v1.3.1
