### ISSUE TITLE
keyboard does not open, when i using this library

### ISSUE THREAD

**Issue by rezaghahremani77** [oneHamidreza/MeowBottomNavigation#45]
Hello guys, I am using this library in an activity and show fragment on a frame layout when user click on any button of bottom navigation. when user want to type anything in any editText, keyboard does not open by showing this message in logcat:
`2020-02-06 07:38:20.352 3650-3650/com.tivasoft.myorder W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection`
and keyboard closed.

**Comment by oneHamidreza** [comment]
i will check it.

**Comment by DevUai** [comment]
Any solution? I'm having the same problem with the Java version.

**Comment by mohammedelnady** [comment]
Untill now there is no solution for that
Also in kotlin code there is abug
And the creator of this lib admit that there is no bug 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by iabduul7** [comment]
@oneHamidreza ? did you fixed the issue???

**Comment by Shamseldienmahmoud** [comment]
@oneHamidreza  did you fixed the issue???

**Comment by iabduul7** [comment]
> @oneHamidreza did you fixed the issue???

their is a simple hack to this problem, I used it in Java version, I don't will it work on Kotlin side or not but here is it.

When you want to set on Menu Click Listeners, change the UI element in this method, I mean in case of fragments just switch between fragments and the other method which causes the issue is OnShowListener, actually this method is called whenever we interact with GUI Input fields i.e. opening keyboard etc. but to make the app execute this method must be called which I don't know why, so just call this method om MeowBottomNavigation reference and do not put any code inside it, you can just put a logcat line. And that's it, it will work.
please test it in Kotlin and let me know if it really works.

**Comment by Shamseldienmahmoud** [comment]
> > @oneHamidreza did you fixed the issue???
> 
> their is a simple hack to this problem, I used it in Java version, I don't will it work on Kotlin side or not but here is it.
> 
> When you want to set on Menu Click Listeners, change the UI element in this method, I mean in case of fragments just switch between fragments and the other method which causes the issue is OnShowListener, actually this method is called whenever we interact with GUI Input fields i.e. opening keyboard etc. but to make the app execute this method must be called which I don't know why, so just call this method om MeowBottomNavigation reference and do not put any code inside it, you can just put a logcat line. And that's it, it will work.
> please test it in Kotlin and let me know if it really works.

please upload ur code in java

**Comment by iabduul7** [comment]
> > > @oneHamidreza did you fixed the issue???
> > 
> > 
> > their is a simple hack to this problem, I used it in Java version, I don't will it work on Kotlin side or not but here is it.
> > When you want to set on Menu Click Listeners, change the UI element in this method, I mean in case of fragments just switch between fragments and the other method which causes the issue is OnShowListener, actually this method is called whenever we interact with GUI Input fields i.e. opening keyboard etc. but to make the app execute this method must be called which I don't know why, so just call this method om MeowBottomNavigation reference and do not put any code inside it, you can just put a logcat line. And that's it, it will work.
> > please test it in Kotlin and let me know if it really works.
> 
> please upload ur code in java



`
bottomNavigation.setOnShowListener(new MeowBottomNavigation.ShowListener() {
            @Override
            public void onShowItem(MeowBottomNavigation.Model item) {
                Log.d("mainActivity1122-show", String.valueOf(item.getId()));
            }
        });

        //it is called whenever an already selected menu button is selected again
        bottomNavigation.setOnReselectListener(new MeowBottomNavigation.ReselectListener() {
            @Override
            public void onReselectItem(MeowBottomNavigation.Model item) {
                // your codes
                Log.d("mainActivity1122-reselected", String.valueOf(item.getId()));
            }
        });
`

just call these two methods, everything will work just fine.

**Comment by iabduul7** [comment]
> > > @oneHamidreza did you fixed the issue???
> > 
> > 
> > their is a simple hack to this problem, I used it in Java version, I don't will it work on Kotlin side or not but here is it.
> > When you want to set on Menu Click Listeners, change the UI element in this method, I mean in case of fragments just switch between fragments and the other method which causes the issue is OnShowListener, actually this method is called whenever we interact with GUI Input fields i.e. opening keyboard etc. but to make the app execute this method must be called which I don't know why, so just call this method om MeowBottomNavigation reference and do not put any code inside it, you can just put a logcat line. And that's it, it will work.
> > please test it in Kotlin and let me know if it really works.
> 
> please upload ur code in java

`
          bottomNavigation.setOnShowListener(new MeowBottomNavigation.ShowListener() {
            @Override
            public void onShowItem(MeowBottomNavigation.Model item) {
                Log.d("mainActivity1122-show", String.valueOf(item.getId()));
            }
        });
`

`
          //it is called whenever an already selected menu button is selected again
        bottomNavigation.setOnReselectListener(new MeowBottomNavigation.ReselectListener() {
            @Override
            public void onReselectItem(MeowBottomNavigation.Model item) {
                // your codes
                Log.d("mainActivity1122-reselected", String.valueOf(item.getId()));
            }
        });
`

just call these two methods like this, everything will work fine.

**Comment by oneHamidreza** [comment]
Duplicate #52

**Comment by mohammedelnady** [comment]
not
