### ISSUE TITLE
Parent layout not transparent background

### ISSUE THREAD

**Issue by tungds** [oneHamidreza/MeowBottomNavigation#47]
Hello,
When I using this lib, BottomNav have a like grey background like picture below. 
![84480506_998877583817121_8423627368035254272_n](https://user-images.githubusercontent.com/5845119/74301716-8628d200-4d86-11ea-8372-b32b15322fca.jpg)

How can I transparent it? Because this color is different my background color, so not good.
Thanks!

**Comment by tungds** [comment]
I resolved problem when I see your sample code. Thanks!

**Comment by sina0935** [comment]
Hello, how did you solve the problem?
