### ISSUE TITLE
Clicked on view multiple times

### ISSUE THREAD

**Issue by imankhorshidi** [oneHamidreza/MeowBottomNavigation#50]
Hi
When we click on all the buttons several times one comes up and causes the user to be dumb.
Check it out thanks.
video : http://s7.picofile.com/file/8388883876/video_2020_02_20_13_41_50.mp4.html
tnx for lib.

**Comment by oneHamidreza** [comment]
I will check it.

**Comment by oneHamidreza** [comment]
Check `v1.3.1`.
