### ISSUE TITLE
 Inverted U-shaped Curve

### ISSUE THREAD

**Issue by mohammadzzz** [oneHamidreza/MeowBottomNavigation#60]
Hi. Thank you for your awesome library. I was wondering that is there some sort of attribute or hack or something like that to achieve an inverted U-shaped curve. Something like this:
![Untitled](https://user-images.githubusercontent.com/8553025/85938432-a6ff5780-b922-11ea-8847-b49360b7969a.png)

**Comment by oneHamidreza** [comment]
no it hasn't this feature

**Comment by mohammadzzz** [comment]
Do you have any idea how can I create a bezier like that? What should I change to get this?

**Comment by oneHamidreza** [comment]
Check out `BezierView`.
