### ISSUE TITLE
How can i set gradient color 

### ISSUE THREAD

**Issue by khaledhnAbusair** [oneHamidreza/MeowBottomNavigation#62]
Hello, please help me for How can i set gradient color rather regular color for this 

now i use this app:mbn_circleColor="@color/white"

![WhatsApp Image 2020-07-01 at 7 34 18 PM](https://user-images.githubusercontent.com/23477307/86269099-edc6a900-bbd1-11ea-9bc8-aba21ecc7758.jpeg)

**Comment by oneHamidreza** [comment]
It doesn't support.
